name: Lint


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  clj-kondo:
    name: Lint with clj-kondo
    if: "!(contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2020.11.07'
      - name: Lint
        run: |
          clj-kondo --lint src/core


  eastwood:
    name: Lint with eastwood
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache gitlibs
        uses: actions/cache@v2
        with:
          path: ~/.gitlibs
          key: ${{ runner.os }}-gitlibs-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-gitlibs-


      - name: Set up jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk'


      - name: Set up clojure-cli
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.727'


      - name: Run eastwood
        run: clojure -A:eastwood
